export interface SalonService {
  id: string;
  name: string;
  price: number;
}

export interface SalonsDatatype {
  key: string;
  salonName: string;
  salonEmail: string;
  salonContact: string;
  salonServices: number;
  salonStaff: number;
  salAdmName: string;
  salAdmEmail: string;
  salAdmContact: string;
  city: string;
  status: "Open" | "Closed";
  category: "Unisex" | "Man" | "Woman" | "Spa" | "Beauty Parler";
  services: SalonService[];
}
export const SalonDetails: SalonsDatatype[] = [
  {
    key: "1",
    salAdmName: "Amit Kapoor",
    salAdmEmail: "admin@glamourstudios.com",
    salAdmContact: "+91 85249 35687",
    salonName: "Glamour Studios",
    salonEmail: "contact@glamourstudios.com",
    salonContact: "+91 98765 43210",
    salonServices: 5,
    salonStaff: 2,
    city: "Mumbai",
    status: "Open",
    category: "Unisex",
    services: [
      { id: "s1-1", name: "Haircut", price: 350 },
      { id: "s1-2", name: "Hair Coloring", price: 1200 },
      { id: "s1-3", name: "Facial", price: 800 },
      { id: "s1-4", name: "Manicure", price: 500 },
      { id: "s1-5", name: "Pedicure", price: 700 },
    ],
  },
  {
    key: "2",
    salAdmName: "Amit Sharma",
    salAdmEmail: "admin@elitehair.com",
    salAdmContact: "+91 87654 32109",
    salonName: "Elite Hair & Beauty",
    salonEmail: "contact@elitehair.com",
    salonContact: "+91 91234 56789",
    salonServices: 3,
    salonStaff: 1,
    city: "Delhi",
    status: "Closed",
    category: "Man",
    services: [
      { id: "s2-1", name: "Haircut", price: 250 },
      { id: "s2-2", name: "Beard Trim", price: 150 },
      { id: "s2-3", name: "Hair Styling", price: 300 },
      { id: "s2-4", name: "Head Massage", price: 250 },
    ],
  },
  {
    key: "3",
    salAdmName: "Priya Verma",
    salAdmEmail: "admin@urbancuts.com",
    salAdmContact: "+91 88990 11223",
    salonName: "Urban Cuts & Colors",
    salonEmail: "hello@urbancuts.com",
    salonContact: "+91 99887 76655",
    salonServices: 3,
    salonStaff: 0,
    city: "Bengaluru",
    status: "Open",
    category: "Woman",
    services: [
      { id: "s3-1", name: "Haircut", price: 450 },
      { id: "s3-2", name: "Hair Spa", price: 900 },
      { id: "s3-3", name: "Facial", price: 1000 },
      { id: "s3-4", name: "Threading", price: 120 },
    ],
  },
  {
    key: "4",
    salAdmName: "Rohit Malhotra",
    salAdmEmail: "admin@luxelocks.com",
    salAdmContact: "+91 90123 45678",
    salonName: "Luxe Locks Salon",
    salonEmail: "info@luxelocks.com",
    salonContact: "+91 90123 45678",
    salonServices: 6,
    salonStaff: 4,
    city: "Hyderabad",
    status: "Open",
    category: "Spa",
    services: [
      { id: "s4-1", name: "Body Massage", price: 1600 },
      { id: "s4-2", name: "Aromatherapy", price: 2200 },
      { id: "s4-3", name: "Facial", price: 1400 },
      { id: "s4-4", name: "Steam Bath", price: 800 },
      { id: "s4-5", name: "Relaxation Therapy", price: 2000 },
    ],
  },
  {
    key: "5",
    salAdmName: "Sneha Iyer",
    salAdmEmail: "admin@thebeautybar.com",
    salAdmContact: "+91 90909 09090",
    salonName: "The Beauty Bar",
    salonEmail: "support@thebeautybar.com",
    salonContact: "+91 90909 09090",
    salonServices: 4,
    salonStaff: 3,
    city: "Chennai",
    status: "Open",
    category: "Beauty Parler",
    services: [
      { id: "s5-1", name: "Facial", price: 900 },
      { id: "s5-2", name: "Manicure", price: 500 },
      { id: "s5-3", name: "Pedicure", price: 700 },
      { id: "s5-4", name: "Waxing", price: 600 },
      { id: "s5-5", name: "Cleanup", price: 400 },
    ],
  },
  {
    key: "6",
    salAdmName: "Karan Mehta",
    salAdmEmail: "admin@chicshine.com",
    salAdmContact: "+91 93456 78123",
    salonName: "Chic & Shine",
    salonEmail: "hello@chicshine.com",
    salonContact: "+91 93456 78123",
    salonServices: 2,
    salonStaff: 1,
    city: "Pune",
    status: "Closed",
    category: "Unisex",
    services: [
      { id: "s6-1", name: "Haircut", price: 300 },
      { id: "s6-2", name: "Hair Styling", price: 350 },
      { id: "s6-3", name: "Head Massage", price: 250 },
    ],
  },
  {
    key: "7",
    salAdmName: "Rohit Singh",
    salAdmEmail: "admin@goldenscissors.com",
    salAdmContact: "+91 95678 91234",
    salonName: "Golden Scissors",
    salonEmail: "contact@goldenscissors.com",
    salonContact: "+91 95678 91234",
    salonServices: 5,
    salonStaff: 2,
    city: "Kolkata",
    status: "Open",
    category: "Man",
    services: [
      { id: "s7-1", name: "Haircut", price: 220 },
      { id: "s7-2", name: "Beard Shaping", price: 180 },
      { id: "s7-3", name: "Hair Coloring", price: 700 },
      { id: "s7-4", name: "Face Cleanup", price: 350 },
    ],
  },
  {
    key: "8",
    salAdmName: "Vikram Patel",
    salAdmEmail: "admin@blissbeauty.com",
    salAdmContact: "+91 98123 45670",
    salonName: "Bliss Beauty Lounge",
    salonEmail: "info@blissbeauty.com",
    salonContact: "+91 98123 45670",
    salonServices: 6,
    salonStaff: 5,
    city: "Ahmedabad",
    status: "Open",
    category: "Spa",
    services: [
      { id: "s8-1", name: "Full Body Massage", price: 1800 },
      { id: "s8-2", name: "Aroma Therapy", price: 2300 },
      { id: "s8-3", name: "Facial", price: 1200 },
      { id: "s8-4", name: "Body Scrub", price: 1500 },
    ],
  },
  {
    key: "9",
    salAdmName: "Anjali Gupta",
    salAdmEmail: "admin@stylestreet.com",
    salAdmContact: "+91 97012 34567",
    salonName: "Style Street Salon",
    salonEmail: "stylestreet@gmail.com",
    salonContact: "+91 97012 34567",
    salonServices: 3,
    salonStaff: 2,
    city: "Jaipur",
    status: "Open",
    category: "Woman",
    services: [
      { id: "s9-1", name: "Haircut", price: 400 },
      { id: "s9-2", name: "Hair Smoothening", price: 2500 },
      { id: "s9-3", name: "Facial", price: 900 },
      { id: "s9-4", name: "Manicure", price: 450 },
    ],
  },
  {
    key: "10",
    salAdmName: "Pooja Khanna",
    salAdmEmail: "admin@crownglory.com",
    salAdmContact: "+91 88990 01122",
    salonName: "Crown & Glory",
    salonEmail: "contact@crownglory.com",
    salonContact: "+91 88990 01122",
    salonServices: 4,
    salonStaff: 3,
    city: "Chandigarh",
    status: "Open",
    category: "Beauty Parler",
    services: [
      { id: "s10-1", name: "Facial", price: 900 },
      { id: "s10-2", name: "Waxing", price: 650 },
      { id: "s10-3", name: "Manicure", price: 500 },
      { id: "s10-4", name: "Pedicure", price: 750 },
    ],
  },
];
