
export interface SalonsDatatype {
  key: string;
  salonName: string;
  salonEmail: string;
  salonContact: string;
  salonServices: number;
  salonStaff: number;
  salAdmName: string;
  salAdmEmail: string;
  salAdmContact: string;
}

export const SalonDetails: SalonsDatatype[] = [
  {
    key: "1",
    salAdmName: "Neha Kapoor",
    salAdmEmail: "admin@glamourstudios.com",
    salAdmContact: "+91 85249 35687",
    salonName: "Glamour Studios",
    salonEmail: "contact@glamourstudios.com",
    salonContact: "+91 98765 43210",
    salonServices: 5,
    salonStaff: 2,
  },
  {
    key: "2",
    salAdmName: "Amit Sharma",
    salAdmEmail: "admin@elitehair.com",
    salAdmContact: "+91 87654 32109",
    salonName: "Elite Hair & Beauty",
    salonEmail: "contact@elitehair.com",
    salonContact: "+91 91234 56789",
    salonServices: 3,
    salonStaff: 1,
  },
  {
    key: "3",
    salAdmName: "Priya Verma",
    salAdmEmail: "admin@urbancuts.com",
    salAdmContact: "+91 88990 11223",
    salonName: "Urban Cuts & Colors",
    salonEmail: "hello@urbancuts.com",
    salonContact: "+91 99887 76655",
    salonServices: 3,
    salonStaff: 0,
  },
  {
    key: "4",
    salAdmName: "Rohit Malhotra",
    salAdmEmail: "admin@luxelocks.com",
    salAdmContact: "+91 90123 45678",
    salonName: "Luxe Locks Salon",
    salonEmail: "info@luxelocks.com",
    salonContact: "+91 90123 45678",
    salonServices: 6,
    salonStaff: 4,
  },
  {
    key: "5",
    salAdmName: "Sneha Iyer",
    salAdmEmail: "admin@thebeautybar.com",
    salAdmContact: "+91 90909 09090",
    salonName: "The Beauty Bar",
    salonEmail: "support@thebeautybar.com",
    salonContact: "+91 90909 09090",
    salonServices: 4,
    salonStaff: 3,
  },
  {
    key: "6",
    salAdmName: "Karan Mehta",
    salAdmEmail: "admin@chicshine.com",
    salAdmContact: "+91 93456 78123",
    salonName: "Chic & Shine",
    salonEmail: "hello@chicshine.com",
    salonContact: "+91 93456 78123",
    salonServices: 2,
    salonStaff: 1,
  },
  {
    key: "7",
    salAdmName: "Pooja Singh",
    salAdmEmail: "admin@goldenscissors.com",
    salAdmContact: "+91 95678 91234",
    salonName: "Golden Scissors",
    salonEmail: "contact@goldenscissors.com",
    salonContact: "+91 95678 91234",
    salonServices: 5,
    salonStaff: 2,
  },
  {
    key: "8",
    salAdmName: "Vikram Patel",
    salAdmEmail: "admin@blissbeauty.com",
    salAdmContact: "+91 98123 45670",
    salonName: "Bliss Beauty Lounge",
    salonEmail: "info@blissbeauty.com",
    salonContact: "+91 98123 45670",
    salonServices: 6,
    salonStaff: 5,
  },
  {
    key: "9",
    salAdmName: "Anjali Gupta",
    salAdmEmail: "admin@stylestreet.com",
    salAdmContact: "+91 97012 34567",
    salonName: "Style Street Salon",
    salonEmail: "stylestreet@gmail.com",
    salonContact: "+91 97012 34567",
    salonServices: 3,
    salonStaff: 2,
  },
  {
    key: "10",
    salAdmName: "Rahul Khanna",
    salAdmEmail: "admin@crownglory.com",
    salAdmContact: "+91 88990 01122",
    salonName: "Crown & Glory",
    salonEmail: "contact@crownglory.com",
    salonContact: "+91 88990 01122",
    salonServices: 4,
    salonStaff: 3,
  },
  {
    key: "11",
    salAdmName: "Meera Joshi",
    salAdmEmail: "admin@velvettouch.com",
    salAdmContact: "+91 98700 12345",
    salonName: "Velvet Touch",
    salonEmail: "info@velvettouch.com",
    salonContact: "+91 98700 12345",
    salonServices: 5,
    salonStaff: 4,
  },
  {
    key: "12",
    salAdmName: "Sahil Arora",
    salAdmEmail: "admin@mirrormagic.com",
    salAdmContact: "+91 97654 32109",
    salonName: "Mirror Magic",
    salonEmail: "hello@mirrormagic.com",
    salonContact: "+91 97654 32109",
    salonServices: 2,
    salonStaff: 1,
  },
  {
    key: "13",
    salAdmName: "Nidhi Saxena",
    salAdmEmail: "admin@polishglow.com",
    salAdmContact: "+91 94567 81230",
    salonName: "Polish & Glow",
    salonEmail: "contact@polishglow.com",
    salonContact: "+91 94567 81230",
    salonServices: 3,
    salonStaff: 2,
  },
  {
    key: "14",
    salAdmName: "Arjun Rao",
    salAdmEmail: "admin@thestylehub.com",
    salAdmContact: "+91 91230 98765",
    salonName: "The Style Hub",
    salonEmail: "admin@thestylehub.com",
    salonContact: "+91 91230 98765",
    salonServices: 7,
    salonStaff: 5,
  },
  {
    key: "15",
    salAdmName: "Kavya Nair",
    salAdmEmail: "admin@pureelegance.com",
    salAdmContact: "+91 99988 87776",
    salonName: "Pure Elegance",
    salonEmail: "info@pureelegance.com",
    salonContact: "+91 99988 87776",
    salonServices: 4,
    salonStaff: 3,
  },
  {
    key: "16",
    salAdmName: "Manish Bansal",
    salAdmEmail: "admin@hairhaven.com",
    salAdmContact: "+91 98877 66554",
    salonName: "Hair Haven",
    salonEmail: "support@hairhaven.com",
    salonContact: "+91 98877 66554",
    salonServices: 3,
    salonStaff: 2,
  },
  {
    key: "17",
    salAdmName: "Ritika Chauhan",
    salAdmEmail: "admin@glowupstudio.com",
    salAdmContact: "+91 93123 45678",
    salonName: "Glow Up Studio",
    salonEmail: "hello@glowupstudio.com",
    salonContact: "+91 93123 45678",
    salonServices: 6,
    salonStaff: 4,
  },
  {
    key: "18",
    salAdmName: "Deepak Sood",
    salAdmEmail: "admin@modernmuse.com",
    salAdmContact: "+91 90234 56781",
    salonName: "Modern Muse Salon",
    salonEmail: "contact@modernmuse.com",
    salonContact: "+91 90234 56781",
    salonServices: 5,
    salonStaff: 3,
  },
  {
    key: "19",
    salAdmName: "Alka Mishra",
    salAdmEmail: "admin@infinitystyles.com",
    salAdmContact: "+91 98765 98765",
    salonName: "Infinity Styles",
    salonEmail: "info@infinitystyles.com",
    salonContact: "+91 98765 98765",
    salonServices: 2,
    salonStaff: 1,
  },
  {
    key: "20",
    salAdmName: "Naveen Kumar",
    salAdmEmail: "admin@aurabeauty.com",
    salAdmContact: "+91 90807 06050",
    salonName: "Aura Beauty Spot",
    salonEmail: "contact@aurabeauty.com",
    salonContact: "+91 90807 06050",
    salonServices: 4,
    salonStaff: 2,
  },
];



  


